In [53]:
import torch

# Tensors

## Creation

In [54]:
# create a tensor
new_tensor = torch.Tensor([[1, 2], [3, 4]])
new_tensor

tensor([[1., 2.],
        [3., 4.]])

In [55]:
# create a 2 x 3 tensor with random values
empty_tensor = torch.Tensor(2, 3)
empty_tensor

tensor([[0.0000e+00, 1.8750e+00, 2.1084e-07],
        [2.7149e-06, 1.0616e-08, 2.1347e-07]])

In [56]:
# create a 2 x 3 tensor with random values between -1and 1
uniform_tensor = torch.Tensor(2, 3).uniform_(-1, 1)
uniform_tensor

tensor([[ 0.7089, -0.3530,  0.5964],
        [-0.3006,  0.5563, -0.9575]])

In [57]:
# create a 2 x 3 tensor with random values from a uniform distribution on the interval [0, 1)
rand_tensor = torch.rand(2, 3)
rand_tensor

tensor([[0.3263, 0.6710, 0.0831],
        [0.3030, 0.9451, 0.7286]])

In [58]:
# create a 2 x 3 tensor of zeros
zero_tensor = torch.zeros(2, 3)
zero_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

# Properties

In [24]:
zero_tensor.device

device(type='cpu')

In [50]:
zero_tensor = zero_tensor.cuda()
zero_tensor.device

device(type='cuda', index=0)

In [59]:
zero_tensor.size()

torch.Size([2, 3])

In [60]:
zero_tensor.shape

torch.Size([2, 3])

In [61]:
zero_tensor.is_cuda

False

In [62]:
zero_tensor.requires_grad

False

In [63]:
print(uniform_tensor)
uniform_tensor.ceil()

tensor([[ 0.7089, -0.3530,  0.5964],
        [-0.3006,  0.5563, -0.9575]])


tensor([[1., -0., 1.],
        [-0., 1., -0.]])

In [64]:
print(uniform_tensor)
uniform_tensor.floor()

tensor([[ 0.7089, -0.3530,  0.5964],
        [-0.3006,  0.5563, -0.9575]])


tensor([[ 0., -1.,  0.],
        [-1.,  0., -1.]])

## Manipulation

In [65]:
new_tensor = torch.Tensor([[1, 2], [3, 4]])
# replace an element at position 0, 0
new_tensor[0][0] = 5
new_tensor          

tensor([[5., 2.],
        [3., 4.]])

In [66]:
# access an element at position 1, 0
print(new_tensor[1][0])          
print(new_tensor[1][0].item())    

tensor(3.)
3.0


In [67]:
new_tensor.view(4,1)

tensor([[5.],
        [2.],
        [3.],
        [4.]])

In [68]:
# transpose
x = torch.randn(2,4)
x

tensor([[ 1.4784, -0.3126, -0.1225,  1.1895],
        [ 1.1842,  1.0726, -0.5321,  0.1376]])

In [69]:
x.t()

tensor([[ 1.4784,  1.1842],
        [-0.3126,  1.0726],
        [-0.1225, -0.5321],
        [ 1.1895,  0.1376]])

In [70]:
# multi-dimensional transpose
x = torch.randn(3,2,3)
print(x.shape)
x

torch.Size([3, 2, 3])


tensor([[[ 0.6281,  0.2725,  1.0569],
         [-0.9354, -0.1302,  0.8358]],

        [[ 0.3430, -0.2651,  0.4714],
         [ 0.2491,  0.1648, -0.1134]],

        [[-0.0053, -0.9981, -0.0560],
         [ 0.0165,  0.9088, -0.2212]]])

In [71]:
x.t()

RuntimeError: t() expects a tensor with <= 2 dimensions, but self is 3D

In [72]:
print(x.transpose(2,1))
print(x.transpose(2,1).shape)

tensor([[[ 0.6281, -0.9354],
         [ 0.2725, -0.1302],
         [ 1.0569,  0.8358]],

        [[ 0.3430,  0.2491],
         [-0.2651,  0.1648],
         [ 0.4714, -0.1134]],

        [[-0.0053,  0.0165],
         [-0.9981,  0.9088],
         [-0.0560, -0.2212]]])
torch.Size([3, 3, 2])


In [73]:
print(x.permute(0,2,1))
print(x.permute(0,2,1).shape)

tensor([[[ 0.6281, -0.9354],
         [ 0.2725, -0.1302],
         [ 1.0569,  0.8358]],

        [[ 0.3430,  0.2491],
         [-0.2651,  0.1648],
         [ 0.4714, -0.1134]],

        [[-0.0053,  0.0165],
         [-0.9981,  0.9088],
         [-0.0560, -0.2212]]])
torch.Size([3, 3, 2])


In [77]:
x.permute(1,2,0)
print(x.permute(1,2,0).shape)

torch.Size([2, 3, 3])


## Matrix 

In [79]:
# point-wise multiplication
A = torch.arange(12).view(3,4).float()
B = torch.arange(12).view(3,4).float()
print(A)
print(B)

A * B

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.]])

In [80]:
A = torch.arange(6).view(2,3).float()
B = torch.arange(6).view(2,3).float()

print(A)
print(B)
print(A.t().mm(B))

tensor([[0., 1., 2.],
        [3., 4., 5.]])
tensor([[0., 1., 2.],
        [3., 4., 5.]])
tensor([[ 9., 12., 15.],
        [12., 17., 22.],
        [15., 22., 29.]])


## Slicing

In [82]:
## slicing examples
slice_tensor = torch.Tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
slice_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [83]:
# elements from every row, first column
print(slice_tensor[:, 0])         # tensor([ 1.,  4.,  7.])

tensor([1., 4., 7.])


In [84]:
# elements from every row, last column
print(slice_tensor[:, -1])        # tensor([ 3.,  6.,  9.])

tensor([3., 6., 9.])


In [85]:
# all elements on the second row
print(slice_tensor[2, :])         # tensor([ 4.,  5.,  6.])

tensor([7., 8., 9.])


In [86]:
# all elements from first two rows
print(slice_tensor[:2, :])        # tensor([[ 1.,  2.,  3.],
                                  #          [ 4.,  5.,  6.]])

tensor([[1., 2., 3.],
        [4., 5., 6.]])
